
import { SubjectType, SubjectMeta, Language, LanguageOption } from './types';

export const LANGUAGES: LanguageOption[] = [
  { code: Language.ZH, label: '简体中文', flag: '🇨🇳' },
  { code: Language.EN, label: 'English', flag: '🇺🇸' },
  { code: Language.MS, label: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: Language.TA, label: 'தமிழ்', flag: '🇮🇳' },
  { code: Language.ES, label: 'Español', flag: '🇪🇸' },
  { code: Language.FR, label: 'Français', flag: '🇫🇷' },
  { code: Language.JA, label: '日本語', flag: '🇯🇵' },
  { code: Language.KO, label: '한국어', flag: '🇰🇷' },
  { code: Language.AR, label: 'العربية', flag: '🇸🇦' },
];

export const UI_STRINGS: Record<Language, any> = {
  [Language.ZH]: {
    brand: "大家庭教育中心",
    slogan: "助力学子，点亮未来",
    about: "关于我们",
    courses: "课程中心",
    hall: "学习大厅",
    start: "点击开始学习",
    knowMore: "了解我们",
    tutorName: "大家庭导师",
    tutorSub: "您的全能学习顾问",
    placeholder: "在此输入您的学习疑问...",
    back: "返回",
    resource: "课程资源",
    normalQuiz: "普通测验",
    aiQuiz: "智能测验",
    notes: "重点笔记",
    openDoc: "打开教材文档",
    score: "得分",
    submit: "提交答案",
    next: "下一题",
    result: "查看结果",
    loading: "正在生成内容...",
    tutorIntro: "你好！我是你的专属导师，有关课程的任何问题，我都能为你解答。你想从哪里开始？",
    chapter: "章节",
    question: "题目",
    correct: "回答正确",
    wrong: "回答错误，正确答案："
  },
  [Language.EN]: {
    brand: "Big Family Education",
    slogan: "Empowering Students",
    about: "About Us",
    courses: "Courses",
    hall: "Study Hall",
    start: "Start Learning",
    knowMore: "Learn More",
    tutorName: "Global Tutor",
    tutorSub: "Your Study Advisor",
    placeholder: "Type questions here...",
    back: "Back",
    resource: "Resources",
    normalQuiz: "Normal Quiz",
    aiQuiz: "AI Quiz",
    notes: "Master Notes",
    openDoc: "Open Materials",
    score: "Score",
    submit: "Submit",
    next: "Next",
    result: "Results",
    loading: "Loading...",
    tutorIntro: "Hello! I am your personal tutor. How can I help you today?",
    chapter: "Chapter",
    question: "Question",
    correct: "Correct",
    wrong: "Incorrect, correct is: "
  },
  [Language.MS]: {
    brand: "Pusat Pendidikan Keluarga",
    slogan: "Menerangi Masa Depan",
    about: "Tentang Kami",
    courses: "Kursus",
    hall: "Dewan Belajar",
    start: "Mula Belajar",
    knowMore: "Ketahui Lebih",
    tutorName: "Mentor Keluarga",
    tutorSub: "Penasihat Anda",
    placeholder: "Taip soalan...",
    back: "Kembali",
    resource: "Sumber",
    normalQuiz: "Kuiz Biasa",
    aiQuiz: "Kuiz AI",
    notes: "Nota Padat",
    openDoc: "Buka Dokumen",
    score: "Markah",
    submit: "Hantar",
    next: "Seterusnya",
    result: "Keputusan",
    loading: "Memuatkan...",
    tutorIntro: "Helo! Saya mentor peribadi anda. Ada apa-apa soalan?",
    chapter: "Bab",
    question: "Soalan",
    correct: "Betul",
    wrong: "Salah, jawapan betul: "
  },
  [Language.TA]: {
    brand: "பெரிய குடும்பக் கல்வி",
    slogan: "மாணவர்களுக்கு அதிகாரம்",
    about: "எங்களைப் பற்றி",
    courses: "பாடங்கள்",
    hall: "படிப்பு கூடம்",
    start: "தொடங்கு",
    knowMore: "மேலும் அறிய",
    tutorName: "ஆசிரியர்",
    tutorSub: "உங்கள் ஆலோசகர்",
    placeholder: "கேள்வி கேட்க...",
    back: "பின்னால்",
    resource: "ஆதாரங்கள்",
    normalQuiz: "சாதாரண வினாடிவினா",
    aiQuiz: "AI வினாடிவினா",
    notes: "குறிப்புகள்",
    openDoc: "ஆவணத்தைத் திற",
    score: "மதிப்பெண்",
    submit: "சமர்ப்பி",
    next: "அடுத்து",
    result: "முடிவு",
    loading: "ஏற்றுகிறது...",
    tutorIntro: "வணக்கம்! நான் உங்கள் ஆசிரியர்.",
    chapter: "அத்தியாயம்",
    question: "கேள்வி",
    correct: "சரி",
    wrong: "தவறு, சரியான பதில்: "
  },
  [Language.ES]: {
    brand: "Educación Gran Familia",
    slogan: "Empoderando Estudiantes",
    about: "Nosotros",
    courses: "Cursos",
    hall: "Aula Virtual",
    start: "Aprender",
    knowMore: "Saber Más",
    tutorName: "Tutor Familiar",
    tutorSub: "Tu Asesor",
    placeholder: "Escribe aquí...",
    back: "Atrás",
    resource: "Recursos",
    normalQuiz: "Prueba Normal",
    aiQuiz: "Prueba AI",
    notes: "Notas Maestras",
    openDoc: "Ver Documento",
    score: "Puntos",
    submit: "Enviar",
    next: "Siguiente",
    result: "Resultados",
    loading: "Cargando...",
    tutorIntro: "¡Hola! Soy tu tutor personal.",
    chapter: "Capítulo",
    question: "Pregunta",
    correct: "Correcto",
    wrong: "Incorrecto, la respuesta es: "
  },
  [Language.JA]: {
    brand: "ビッグファミリー教育",
    slogan: "学生に力を与える",
    about: "私たちについて",
    courses: "コース",
    hall: "学習ホール",
    start: "学習開始",
    knowMore: "もっと知る",
    tutorName: "ファミリーメンター",
    tutorSub: "学習アドバイザー",
    placeholder: "質問を入力...",
    back: "戻る",
    resource: "教材",
    normalQuiz: "通常テスト",
    aiQuiz: "AIテスト",
    notes: "要点ノート",
    openDoc: "教材を開く",
    score: "スコア",
    submit: "送信",
    next: "次へ",
    result: "结果",
    loading: "読み込み中...",
    tutorIntro: "こんにちは！専属講師です。",
    chapter: "章",
    question: "问题",
    correct: "正解",
    wrong: "不正解、正解は： "
  },
  [Language.KO]: {
    brand: "빅 패밀리 교육",
    slogan: "학생에게 힘을",
    about: "회사 소개",
    courses: "강좌",
    hall: "학습 홀",
    start: "학습 시작",
    knowMore: "더 보기",
    tutorName: "패밀리 튜터",
    tutorSub: "학습 컨설턴트",
    placeholder: "질문 입력...",
    back: "뒤로",
    resource: "학습 리소스",
    normalQuiz: "일반 퀴즈",
    aiQuiz: "AI 퀴즈",
    notes: "핵심 노트",
    openDoc: "교재 열기",
    score: "점수",
    submit: "제출",
    next: "다음",
    result: "결과",
    loading: "로딩 중...",
    tutorIntro: "안녕하세요! 전담 튜터입니다.",
    chapter: "장",
    question: "문항",
    correct: "정답",
    wrong: "오답, 정답은: "
  },
  [Language.AR]: {
    brand: "تعليم العائلة الكبيرة",
    slogan: "تمكين الطلاب",
    about: "من نحن",
    courses: "الدورات",
    hall: "قاعة التعلم",
    start: "ابدأ الآن",
    knowMore: "معرفة المزيد",
    tutorName: "معلم العائلة",
    tutorSub: "مستشارك التعليمي",
    placeholder: "اكتب هنا...",
    back: "عودة",
    resource: "الموارد",
    normalQuiz: "اختبار عادي",
    aiQuiz: "اختبار ذكي",
    notes: "ملاحظات الخبراء",
    openDoc: "فتح المواد",
    score: "النتيجة",
    submit: "إرسال",
    next: "التالي",
    result: "النتائج",
    loading: "جاري التحميل...",
    tutorIntro: "مرحباً! أنا معلمك الخاص.",
    chapter: "الفصل",
    question: "السؤال",
    correct: "صحيح",
    wrong: "خطأ، الجواب الصحيح: "
  },
  [Language.FR]: {
    brand: "Éducation Grande Famille",
    slogan: "Responsabiliser les Étudiants",
    about: "À Propos",
    courses: "Cours",
    hall: "Salle d'Étude",
    start: "Commencer",
    knowMore: "Savoir Plus",
    tutorName: "Tuteur de Famille",
    tutorSub: "Votre Conseiller",
    placeholder: "Tapez ici...",
    back: "Retour",
    resource: "Ressources",
    normalQuiz: "Quiz Normal",
    aiQuiz: "Quiz AI",
    notes: "Notes de Maître",
    openDoc: "Ouvrir les Documents",
    score: "Score",
    submit: "Envoyer",
    next: "Suivant",
    result: "Résultats",
    loading: "Chargement...",
    tutorIntro: "Bonjour ! Je suis votre tuteur personnel.",
    chapter: "Chapter",
    question: "Question",
    correct: "Correct",
    wrong: "Incorrect, la réponse est : "
  }
};

export const SUBJECTS: SubjectMeta[] = [
  {
    id: SubjectType.CHINESE,
    title: '华文 (Chinese)',
    icon: '🏮',
    color: '#ef4444',
    gradient: 'from-red-500 to-orange-400',
    description: '深入了解中华文化，提升文学造诣与写作技巧。'
  },
  {
    id: SubjectType.SCIENCE,
    title: '科学 (Science)',
    icon: '🧪',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-400',
    description: '探索自然界的奥秘，培养科学思维与实验精神。'
  },
  {
    id: SubjectType.MATH,
    title: '数学 (Math)',
    icon: '📐',
    color: '#3b82f6',
    gradient: 'from-blue-500 to-indigo-400',
    description: '掌握逻辑与计算能力，解决生活中的各种难题。'
  },
  {
    id: SubjectType.GEOGRAPHY,
    title: '地理 (Geography)',
    icon: '🌍',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-yellow-400',
    description: '俯瞰世界，了解地形地貌、气候变化与人类社会。'
  },
  {
    id: SubjectType.HISTORY,
    title: '历史 (History)',
    icon: '📜',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-400',
    description: '以史为鉴，了解过去重大事件对现代世界的影响。'
  },
  {
    id: SubjectType.RBT,
    title: '设计与技术 (RBT)',
    icon: '⚙️',
    color: '#64748b',
    gradient: 'from-slate-500 to-gray-400',
    description: '动手实践，学习基础工程原理、电子技术与现代设计。'
  }
];
